### PR TITLE
Adds codelense action for update snapshot

### PR DESCRIPTION
**Pull request by tinganho**
I added a code lense action for an update snapshot action. It just adds the command line flag `-u` when pressed.

### CODE REVIEW

**Comment by tinganho** [comment]
I skipped adding the equivalent actions on explorer and editor. Since they require icons to finish. I guess you can easily add those.

**Comment by nithinpeter** [comment]
Hey 👋 Thanks for the PR. 

We will show the new code lens action for all tests? Can we make it to appear only for tests which has snapshot assertions? 

I think not many people will have snapshot tests and we might end up polluting their UI by adding an action for all.

We can probably look at the test and see if it has “toMatchSnapshot” string in it (or something similar)? If that’s hard to do, add a config option to show/hide (hidden by default) the code lens action. 

What do you think?

**Comment by tinganho** [comment]
Yeah, I think it sounds good to filter the code lense based on whether it is needed or not. Though, I think we need to add a config to match based on custom snapshot matchers as well. My use case, is not the built-in `toMatchSnapshot`, but I use `toMatchImageSnapshot` from [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot).

https://jestjs.io/docs/en/expect#custom-snapshot-matchers

**Comment by tinganho** [comment]
Ok, I updated the PR to reflect my above comment. It doesn't work for `it.each` yet. There is a bug in `jest-editor-support`.

**Comment by tinganho** [comment]
Logged a ticket in `jest-editor-support` https://github.com/jest-community/jest-editor-support/issues/37

**Comment by nithinpeter** [comment]
Very nice! Thanks, I will release a version with these changes soon.

**Pull request merged**
