### PR TITLE
feat: jest run options

### PR DESCRIPTION
**Pull request by fishonweb**
Issue #15 

Add run options array in extension setting to be able to customize Jest CLI run (https://jestjs.io/docs/en/cli.html#options)

image

### CODE REVIEW

**Comment by fishonweb** [comment]
@fishonweb don't forget to add it to readme

**Comment by nithinpeter** [comment]
Hey, thanks for the PR. It is really nice to have this config option. 

Can you please resolve the conflicts and I will merge the PR. 👍

**Comment by fishonweb** [comment]
Great! Thank you @nithinpeter !

**Comment by nithinpeter** [comment]
Never mind, I have resolved it myself. Also updated the readme. v4.0.0 of the extension will include this changes. 

Thanks.

**Pull request merged**
